allow_fallback: false
analysis_isotope: radon
allow_negative_baseline: false
allow_negative_activity: false
calibration:
  slope_MeV_per_ch: null
  intercept_MeV: null
  float_slope: false
  sigma_E_init: null
  peak_widths: null
spectral_fit:
  peak_search_method: prominence
  peak_search_cwt_widths: null
  refit_aic_threshold: 2.0
time_fit:
  window_po214:
  - 7.55
  - 7.80
  window_po218:
  - 5.90
  - 6.10
  window_po210:
  - 5.25
  - 5.37
  eff_po214: 0.25               # ZnS(Ag) typical; change if you measured it
  bkg_po214: [0.0, 0.2]         # allow a flat residual background
  min_counts: 20
